# Generated by Django 5.0.4 on 2024-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
