# Generated by Django 5.0.4 on 2024-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0002_contactusform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusform',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
