# Generated by Django 5.0.4 on 2024-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0003_contactusform_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='product_image',
            field=models.FileField(default=None, upload_to='products'),
        ),
    ]
