# Generated by Django 5.0.4 on 2024-08-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0004_productinventory_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteOrder',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_mobile_number', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_id', models.CharField(max_length=50)),
                ('is_paid', models.BooleanField()),
                ('is_accepted', models.BooleanField()),
                ('order_date', models.DateField(auto_now=True)),
                ('bill_Amount', models.FloatField()),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appone.websiteorder')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appone.productinventory')),
            ],
        ),
    ]
