# Generated by Django 5.0.4 on 2024-08-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0005_websiteorder_websiteorderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteorder',
            old_name='bill_Amount',
            new_name='bill_amount',
        ),
    ]
