# Generated by Django 5.0.4 on 2024-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0006_rename_bill_amount_websiteorder_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
    ]
