# Generated by Django 5.0.4 on 2024-09-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0007_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteorderitems',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='Appone.websiteorder'),
        ),
        migrations.AlterField(
            model_name='websiteorderitems',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Appone.productinventory'),
        ),
    ]
