# Generated by Django 5.0.4 on 2024-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0008_alter_websiteorderitems_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='mrp',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
