# Generated by Django 5.0.4 on 2024-09-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0009_productinventory_mrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteorder',
            old_name='bill_amount',
            new_name='bill_mrp_amount',
        ),
        migrations.AddField(
            model_name='websiteorder',
            name='bill_net_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='websiteorder',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
